name: yourseatgraduationproject
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev.

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.4.3
  cupertino_icons: ^1.0.6
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.2
  flutter_localization: ^0.2.2
  flutter_screenutil: ^5.9.3
  bot_toast: ^4.1.3
  # dots_indicator: ^3.0.0
  # either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  # flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_localizations: # Fixed null issue, added SDK here.
    sdk: flutter
  # font_awesome_flutter: ^10.7.0
  # get_it: ^7.7.0
  hive_flutter: ^1.1.0
  curved_labeled_navigation_bar: ^2.0.2
  # iconsax: ^0.0.8
  # intl: ^0.19.0
  # shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
flutter_intl:
  enabled: true
