name: yourseatgraduationproject

description: "A new Flutter project."

publish_to: 'none' # Prevents accidental publishing to pub.dev.

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  calendar_timeline: ^1.1.3
  table_calendar: ^3.0.0
  animate_do: ^3.3.4
  bot_toast: ^4.1.3
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.4.3
  cupertino_icons: ^1.0.6
  curved_labeled_navigation_bar: ^2.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.2
  firebase_auth: ^5.3.1
  firebase_app_check: ^0.3.1+4
  url_launcher: ^6.1.5
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  provider: ^6.0.5
  device_preview:

  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_localization: ^0.2.2
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.1
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  otp_pin_field: ^1.3.1
  timeline_calendar: ^1.0.2
  flutter_facebook_auth: any
  font_awesome_flutter: any
  google_sign_in: any
  intl_utils: ^2.8.7
  neon_widgets: ^2.0.0
  readmore: ^3.0.0
  image_picker: ^1.1.2
#  image_cropper: ^8.0.2
  email_otp_auth: ^1.1.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path:  "assets/images/splash.png"  # ضع مسار الصورة هنا
  adaptive_icon_background: "#ffffff"  # لون الخلفية للأيقونة التكيفية (أندرويد)
  # adaptive_icon_foreground: "assets/icons/app_icon_adaptive.png"  # صورة المقدمة للأيقونة التكيفية
